"use client";
import { usePageReady } from "@/hooks/usePageReady";
import { Box, Container, Typography, Paper, Stack, Divider, useTheme, alpha } from "@mui/material";
import GavelIcon from "@mui/icons-material/Gavel";

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using ChessAgine ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. ChessAgine reserves the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.`,
  },
  {
    title: "2. Description of Service",
    body: `ChessAgine is a chess analysis platform that provides tools including engine analysis (Stockfish), neural network evaluation (Leela Chess Zero, Maia), large language model integrations, puzzle solving, game review, and bot play functionality. The Service is provided as-is for educational and entertainment purposes.`,
  },
  {
    title: "3. User Accounts",
    body: `User authentication is managed by a third-party authentication provider. By creating an account, you agree to provide accurate and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.`,
  },
  {
    title: "4. Acceptable Use",
    body: `You agree not to use the Service for any unlawful purpose or in a way that could harm ChessAgine or other users. Prohibited activities include: attempting to reverse-engineer or abuse the Service's APIs; using automated bots to create accounts or abuse free tier limits; uploading malicious content; or circumventing any rate limits or access controls.`,
  },
  {
    title: "5. API Keys and Third-Party Services",
    body: `The Service allows you to connect third-party API keys (e.g., OpenAI, Anthropic, Google). These keys are stored locally in your browser and are never transmitted to or stored on ChessAgine servers. You are solely responsible for the usage and security of your own API keys and for any charges incurred through those third-party services.`,
  },
  {
    title: "6. Intellectual Property",
    body: `ChessAgine is free software released under the GNU Affero General Public License v3.0 (AGPL-3.0). You are free to use, copy, modify, and distribute the source code in accordance with that license. The ChessAgine name and logo remain the property of the ChessAgine project. Chess content from Lichess is used under their respective open licenses.`,
  },
  {
    title: "7. Subscriptions and Payments",
    body: `Certain premium features may be available through a paid subscription. Subscriptions are billed on the terms displayed at purchase. You may cancel at any time. Free tier usage is subject to daily and monthly limits as displayed in the application.`,
  },
  {
    title: "8. Disclaimer of Warranties",
    body: `The Service is provided "as is" without warranty of any kind, express or implied. ChessAgine does not warrant that the Service will be uninterrupted, error-free, or free of harmful components. Chess analysis results are provided for informational purposes only and should not be relied upon for competitive or commercial purposes.`,
  },
  {
    title: "9. Limitation of Liability",
    body: `To the maximum extent permitted by applicable law, ChessAgine and its contributors shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, even if advised of the possibility of such damages.`,
  },
  {
    title: "10. Termination",
    body: `ChessAgine reserves the right to suspend or terminate your access to the Service at any time for any reason, including violation of these Terms. You may stop using the Service at any time. Upon termination, provisions that by their nature should survive will remain in effect.`,
  },
  {
    title: "11. Governing Law",
    body: `These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the Service shall be resolved through good-faith negotiation where possible.`,
  },
  {
    title: "12. Agine Chat — AI Chess Assistant",
    body: `ChessAgine includes Agine Chat, an AI-powered chess assistant. By using Agine Chat you agree to the following: (a) Agine Chat is provided for chess education and entertainment purposes only. (b) You must not use any output from Agine Chat for unlawful, harmful, abusive, or deceptive purposes. (c) AI responses are generated by third-party large language models and may occasionally be inaccurate, incomplete, or inconsistent — they should not be treated as authoritative chess or legal advice. (d) You must not attempt to manipulate Agine Chat into producing content that violates these Terms or applicable law, including through prompt injection or jailbreaking techniques. (e) ChessAgine is not liable for any decisions made based on Agine Chat output. (f) Conversation content is not stored on ChessAgine servers. (g) Usage of underlying AI models is subject to the respective provider's terms of service (OpenAI, Anthropic, Google, etc.). By sending a message in Agine Chat, you confirm your acceptance of these conditions.`,
  },
  {
    title: "13. Contact",
    body: `If you have questions about these Terms of Service, please reach out to us via our Discord community`,
  },
];

export default function TermsPage() {
  usePageReady();
  const theme = useTheme();
  const primary = theme.palette.primary.main;

  return (
    <Box sx={{ minHeight: "100vh", bgcolor: "background.default", py: { xs: 4, md: 7 } }}>
      <Container maxWidth="md">
        {/* Header */}
        <Stack direction="row" alignItems="center" spacing={2} sx={{ mb: 1.5 }}>
          <Box sx={{
            width: 44, height: 44, borderRadius: 2,
            bgcolor: alpha(primary, 0.1), display: "flex",
            alignItems: "center", justifyContent: "center", color: primary,
          }}>
            <GavelIcon sx={{ fontSize: 22 }} />
          </Box>
          <Box>
            <Typography variant="h4" fontWeight={800} sx={{ lineHeight: 1.15, fontSize: { xs: "1.6rem", md: "2rem" } }}>
              Terms of Service
            </Typography>
            <Typography variant="caption" sx={{ color: "text.disabled" }}>
              Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
            </Typography>
          </Box>
        </Stack>

        <Typography variant="body2" sx={{ color: "text.secondary", mb: 4, ml: 7, lineHeight: 1.65 }}>
          Please read these terms carefully before using ChessAgine. They govern your use of the platform.
        </Typography>

        <Divider sx={{ mb: 4 }} />

        <Stack spacing={3}>
          {sections.map((s) => (
            <Paper key={s.title} elevation={0} sx={{
              p: 3, borderRadius: 2,
              border: `1px solid ${theme.palette.divider}`,
              bgcolor: "background.paper",
            }}>
              <Typography variant="subtitle1" fontWeight={700} sx={{ mb: 1, color: primary, fontSize: "0.95rem" }}>
                {s.title}
              </Typography>
              <Typography variant="body2" sx={{ color: "text.secondary", lineHeight: 1.75, fontSize: "0.87rem" }}>
                {s.body}
              </Typography>
            </Paper>
          ))}
        </Stack>

        <Box sx={{ mt: 5, p: 2.5, borderRadius: 2, bgcolor: alpha(primary, 0.06), border: `1px solid ${alpha(primary, 0.15)}`, textAlign: "center" }}>
          <Typography variant="body2" sx={{ color: "text.secondary", fontSize: "0.82rem" }}>
            Questions? Join our{" "}
            <Typography component="a" href="https://discord.gg/bCPwe6XWcH" target="_blank" rel="noopener noreferrer"
              sx={{ color: primary, fontWeight: 600, textDecoration: "none", "&:hover": { textDecoration: "underline" } }}>
              Discord community
            </Typography>
            {" "}and we&apos;ll be happy to help.
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}